### ISSUE TITLE
Streampi problems with Run Command and Run Executable

### ISSUE THREAD

**Issue by zebsy** [ladiesman6969/streampi_server#19]
Hello,

I had recently made myself a working Streampi setup fully functional with twitch chat functions and obs functions but when trying to execute commands and open executable it always doesn't work.

I have tried PowerShell command variations:
`cmd.exe --% /c call sendKeys.bat "discord" ""`

I have tried cmd commands:
`call sendKeys.bat "discord" ""`

But both didn't work, with the cmd command I got the 'Cannot run program “…” error=2, No such file or directory' error, the powershell didn't give such an error.

Both commands worked in their respective terminal.

And concerning the Run Executable function it never worked, when selecting the executable location and then testing it never reacted on the hosting machine.

I could imagine that specific arguments would be needed but in this case i am not as experienced.

Thanks for the help in advanced.

**Comment by rnayabed** [comment]
`cmd.exe` part is redundant. Can you try something like `absolute/path/to/sendKeys.bat "discord"` and see whether it works or not?
Always make sure to provide the absolute path of any executable you are trying to run.

Also, this repository has been abandoned. The new one for tracking issues and development (for server) is [stream-pi/server](https://github.com/stream-pi/server)
